import { z } from "zod"
const nonEmpty = z.string().min(1)
export const assetTypes = ["ESTABLISHING_SHOT","HUMAN_ACTION","DETAIL_INSERT","EVIDENCE_INSERT","MECHANISM_GRAPHIC","SCREEN_RECREATION","TEXT_EMPHASIS","MAP_OR_DIAGRAM","EMOTIONAL_HOLD","CONSEQUENCE_SHOT","PROTECTION_GRAPHIC","TRANSITION_ASSET"] as const
export const visualFunctions = ["ORIENT","SHOW","PROVE","EXPLAIN","CONTRAST","EMOTION","OPENLOOP","PAYOFF","TRANSITION","BREATHINGSPACE"] as const
export const ProductionConstraintsSchema = z.object({ maxBudgetUnits:z.number().nonnegative(), availableAssetTypes:z.array(z.enum(assetTypes)).min(1), wordsPerMinute:z.number().positive(), runtimeToleranceSeconds:z.number().nonnegative(), pauseMarginRatio:z.number().min(0).max(1) })
export const TopicBriefSchema = z.object({ projectId:nonEmpty,niche:nonEmpty,country:nonEmpty,language:nonEmpty,audience:nonEmpty,objective:nonEmpty,targetRuntimeSeconds:z.number().positive(),productionConstraints:ProductionConstraintsSchema,editorialConstraints:z.array(nonEmpty),researchWindow:z.object({from:z.iso.datetime(),to:z.iso.datetime()}).refine(v=>v.from<=v.to).optional() })
export const TopicCandidateSchema = z.object({ schemaVersion:nonEmpty,projectId:nonEmpty,topicId:nonEmpty,title:nonEmpty,coreQuestion:nonEmpty,angle:nonEmpty,audiencePromise:nonEmpty,whyNow:nonEmpty.optional(),topOfFunnelPotential:z.number().min(0).max(1),productionComplexity:z.number().min(0).max(1),evidenceAvailability:z.number().min(0).max(1),editorialRisk:z.number().min(0).max(1),monetizationContext:nonEmpty,candidateScore:z.number().min(0).max(1),confidence:z.number().min(0).max(1),sourceRefs:z.array(nonEmpty),status:z.enum(["CANDIDATE","GREENLIT","NEEDS_RESEARCH","HUMAN_REQUIRED","REJECTED"]),warnings:z.array(z.string()),blockingErrors:z.array(z.string()) }).superRefine((v,c)=>{if(v.confidence<.7&&v.status==="GREENLIT")c.addIssue({code:"custom",message:"confidence below 0.70 cannot be greenlit",path:["status"]});if(v.blockingErrors.length&&v.status==="GREENLIT")c.addIssue({code:"custom",message:"blocking errors prevent greenlight",path:["blockingErrors"]})})
const claimBase={claimId:nonEmpty,claimText:nonEmpty,sourceQuality:z.enum(["PRIMARY","SECONDARY","LOW","MISSING"]),sourceDate:z.iso.datetime().optional(),supportLevel:z.number().min(0).max(1),contradictions:z.array(z.string()),allowedWording:nonEmpty,forbiddenWording:nonEmpty,visualTreatment:z.enum(["FACTUAL_EVIDENCE","DRAMATIZATION","ILLUSTRATION","NONE"])}
export const EvidenceClaimSchema=z.discriminatedUnion("classification",[
 z.object({...claimBase,classification:z.literal("VERIFIED"),sourceRefs:z.tuple([nonEmpty],nonEmpty),status:z.literal("ACTIVE")}),
 z.object({...claimBase,classification:z.literal("INFERRED"),sourceRefs:z.array(nonEmpty),status:z.literal("ACTIVE")}),
 z.object({...claimBase,classification:z.literal("UNCERTAIN"),sourceRefs:z.array(nonEmpty),status:z.literal("ACTIVE")}),
 z.object({...claimBase,classification:z.literal("UNSUPPORTED"),sourceRefs:z.array(nonEmpty),status:z.literal("REMOVE")})])
export const EvidenceMatrixSchema=z.object({schemaVersion:nonEmpty,projectId:nonEmpty,claims:z.array(EvidenceClaimSchema).min(1),unresolvedQuestions:z.array(z.string()),contradictions:z.array(z.string()),status:z.enum(["DRAFT","VERIFIED","NEEDS_RESEARCH","BLOCKED"])}).superRefine((v,c)=>{if(v.status==="VERIFIED"&&v.claims.some(x=>x.sourceRefs.length===0||x.classification==="UNSUPPORTED"))c.addIssue({code:"custom",message:"verified matrix cannot contain unsourced or unsupported claims"})})
export const VisualJobSchema=z.discriminatedUnion("kind",[z.object({kind:z.literal("VISUAL"),job:z.enum(visualFunctions),description:nonEmpty,required:z.boolean()}),z.object({kind:z.literal("EVIDENCE"),job:z.literal("PROVE"),claimId:nonEmpty,representation:nonEmpty,required:z.literal(true)})])
export const AssetRequestSchema=z.discriminatedUnion("kind",[z.object({kind:z.literal("GENERATED"),assetType:z.enum(assetTypes),specification:nonEmpty,budgetUnits:z.number().nonnegative()}),z.object({kind:z.literal("SOURCE"),assetType:z.literal("EVIDENCE_INSERT"),sourceRef:nonEmpty,specification:nonEmpty,budgetUnits:z.number().nonnegative()}),z.object({kind:z.literal("DRAMATIZATION"),assetType:z.enum(assetTypes),disclosure:nonEmpty,specification:nonEmpty,budgetUnits:z.number().nonnegative()})])
export const TransitionPlanSchema=z.discriminatedUnion("kind",[z.object({kind:z.literal("CUT"),rationale:nonEmpty}),z.object({kind:z.literal("DISSOLVE"),durationSec:z.number().positive(),rationale:nonEmpty}),z.object({kind:z.literal("GRAPHIC_MATCH"),matchElement:nonEmpty,rationale:nonEmpty})])
export const SoundIntentSchema=z.object({soundId:nonEmpty,beatId:nonEmpty,intent:z.enum(["TENSION","CLARITY","IMPACT","SILENCE","RELIEF"]),description:nonEmpty})
export const ScriptBeatSchema=z.object({beatId:nonEmpty,sequenceId:nonEmpty,startSec:z.number().nonnegative(),endSec:z.number().positive(),section:z.enum(["HOOK","ORIENTATION","DEVELOPMENT","TURNING_POINT","PAYOFF","CLOSING"]),dramaticFunction:nonEmpty,informationGoal:nonEmpty,audienceStateBefore:nonEmpty,audienceStateAfter:nonEmpty,mainClaimId:nonEmpty.optional(),narration:z.string(),delivery:nonEmpty,claimIds:z.array(nonEmpty),evidenceIds:z.array(nonEmpty),visualJobs:z.array(VisualJobSchema),assetRequests:z.array(AssetRequestSchema),soundIntent:SoundIntentSchema.optional(),transition:TransitionPlanSchema.optional(),openLoopIds:z.array(nonEmpty),postProductionRequirements:z.array(nonEmpty)}).superRefine((v,c)=>{if(v.endSec<=v.startSec)c.addIssue({code:"custom",message:"beat duration must be positive"});if(v.visualJobs.some(j=>j.required)&&v.assetRequests.length===0)c.addIssue({code:"custom",message:"required visual needs an asset"})})
export const OpenLoopSchema=z.object({loopId:nonEmpty,question:nonEmpty,openedAtBeatId:nonEmpty,progressBeatIds:z.array(nonEmpty),closedAtBeatId:nonEmpty.optional(),answerClaimIds:z.array(nonEmpty),status:z.enum(["OPEN","CLOSED","UNCERTAIN","BLOCKED"])}).superRefine((v,c)=>{if(v.status==="CLOSED"&&(!v.closedAtBeatId||!v.answerClaimIds.length))c.addIssue({code:"custom",message:"closed loop needs destination and answer"})})
const AssetBudgetSchema=z.object({generatedVideo:z.number().nonnegative(),generatedImage:z.number().nonnegative(),evidenceInsert:z.number().nonnegative(),motionGraphic:z.number().nonnegative(),mapOrDiagram:z.number().nonnegative(),atmosphericImage:z.number().nonnegative(),manualReviewSlots:z.number().nonnegative()})
const finding=z.object({code:nonEmpty,severity:z.enum(["WARNING","BLOCKING"]),message:nonEmpty,refs:z.array(z.string())})
export const ScriptQCSchema=z.discriminatedUnion("decision",[z.object({decision:z.literal("SCRIPT_APPROVED"),findings:z.array(finding).refine(x=>!x.some(f=>f.severity==="BLOCKING")),estimatedRuntimeSeconds:z.number().nonnegative()}),z.object({decision:z.enum(["NEEDS_SCRIPT_REVISION","NEEDS_RESEARCH","HUMAN_REQUIRED","BLOCKED"]),findings:z.array(finding),estimatedRuntimeSeconds:z.number().nonnegative(),blockingReasons:z.array(nonEmpty).min(1)})])
export const ScriptPackageSchema=z.object({schemaVersion:nonEmpty,projectId:nonEmpty,runId:nonEmpty,topicId:nonEmpty,status:z.enum(["DRAFT","NEEDS_RESEARCH","NEEDS_REVISION","SCRIPT_APPROVED","BLOCKED"]),targetRuntimeSeconds:z.number().positive(),narrationWordCount:z.number().int().nonnegative(),storyBible:z.object({coreQuestion:nonEmpty,audiencePromise:nonEmpty,thesis:nonEmpty,tone:nonEmpty,structure:z.array(nonEmpty).min(1),structureDeviationReason:nonEmpty.optional()}),scriptMaster:nonEmpty,semanticUnits:z.array(nonEmpty),sequences:z.array(z.object({sequenceId:nonEmpty,title:nonEmpty,purpose:nonEmpty,beatIds:z.array(nonEmpty).min(1)})).min(1),beats:z.array(ScriptBeatSchema).min(1),openLoops:z.array(OpenLoopSchema),evidenceMatrix:EvidenceMatrixSchema,assetBudget:AssetBudgetSchema,assetUsage:z.array(z.object({assetType:z.enum(assetTypes),planned:z.number().nonnegative(),budgetCategory:z.enum(["generatedVideo","generatedImage","evidenceInsert","motionGraphic","mapOrDiagram","atmosphericImage","manualReviewSlots"]),overage:z.number().nonnegative(),groupable:z.boolean(),recommendation:z.string().optional()})),emotionalCurve:z.array(z.object({atSec:z.number().nonnegative(),intensity:z.number().min(0).max(1),label:nonEmpty})),soundMap:z.array(SoundIntentSchema),continuityBible:z.object({entities:z.array(z.string()),locations:z.array(z.string()),chronology:z.array(z.string()),visualRules:z.array(z.string()),disclaimers:z.array(z.string())}),qc:ScriptQCSchema,warnings:z.array(z.string()),blockingErrors:z.array(z.string()),nextAgent:z.string().optional()}).superRefine((v,c)=>{if(v.status==="SCRIPT_APPROVED"&&(v.blockingErrors.length||v.qc.decision!=="SCRIPT_APPROVED"))c.addIssue({code:"custom",message:"approved package cannot have blocking errors"})})
