import {z} from "zod"
const rep=z.enum(["REAL_EVIDENCE","RECONSTRUCTION","DRAMATIZATION","FICTIONAL_INTERFACE","ILLUSTRATION","EXPLANATORY_GRAPHIC"])
export const editSequenceSchema=z.object({sequenceId:z.string().min(1),title:z.string().min(1),startSec:z.number().nonnegative(),endSec:z.number().positive(),dramaticFunction:z.enum(["COLD_OPEN","ORIENTATION","FIRST_PROOF","MECHANISM","ESCALATION","TURNING_POINT","CONSEQUENCE","PAYOFF","PROTECTION","CLOSING"]),informationGoal:z.string().min(1),audienceStateBefore:z.string().min(1),audienceStateAfter:z.string().min(1),emotionalEnergy:z.number().min(0).max(1),narrativeClaimIds:z.array(z.string()),evidenceIds:z.array(z.string()),visualStrategy:z.string().min(1),audioStrategy:z.string().min(1),shotIds:z.array(z.string()).min(1),transitionIn:z.string().optional(),transitionOut:z.string().optional(),openLoopIds:z.array(z.string())}).refine(v=>v.endSec>v.startSec)
export const editShotSchema=z.object({shotId:z.string().min(1),sequenceId:z.string().min(1),startSec:z.number().nonnegative(),endSec:z.number().positive(),durationSec:z.number().positive(),shotType:z.enum(["ESTABLISHING_SHOT","MEDIUM_HUMAN_ACTION","CLOSE_UP","DETAIL_INSERT","EVIDENCE_INSERT","MECHANISM_GRAPHIC","SCREEN_RECREATION","TEXT_EMPHASIS","MAP_OR_DIAGRAM","EMOTIONAL_HOLD","CONSEQUENCE_SHOT","PROTECTION_GRAPHIC","TRANSITION_SHOT"]),assetType:z.enum(["GENERATED_VIDEO","GENERATED_IMAGE","EVIDENCE_ASSET","MOTION_GRAPHIC","REAL_SOURCE_ASSET","POST_PRODUCTION_TEXT","MANUAL_EDIT"]),shotRole:z.enum(["ORIENT","SHOW","PROVE","EXPLAIN","CONTRAST","EMOTION","OPEN_LOOP","PAYOFF","TRANSITION"]),purpose:z.string().min(1),visualDescription:z.string().min(1),informationShown:z.string().min(1),narrationSupport:z.enum(["COMPLEMENT","CONTEXTUALIZE","CONTRAST","PROVE","NONE"]),claimIds:z.array(z.string()),evidenceIds:z.array(z.string()),representationType:rep,labelRequired:z.boolean(),characterRefs:z.array(z.string()),locationRefs:z.array(z.string()),objectRefs:z.array(z.string()),continuityConstraints:z.array(z.string()),cameraIntent:z.string().optional(),lightingIntent:z.string().optional(),paletteIntent:z.string().optional(),motionIntent:z.string().optional(),transitionIn:z.string().optional(),transitionOut:z.string().optional(),soundIntentIds:z.array(z.string()),assetRequestId:z.string().min(1),rejectionCriteria:z.array(z.string()).min(1)}).refine(v=>Math.abs(v.endSec-v.startSec-v.durationSec)<.001).refine(v=>v.representationType==="REAL_EVIDENCE"||v.labelRequired,{message:"Representação sintética exige rótulo"})
export const editAssetRequestSchema=z.object({assetRequestId:z.string().min(1),shotId:z.string().min(1),function:z.string().min(1),assetType:z.string().min(1),priority:z.enum(["MUST_HAVE","SHOULD_HAVE","OPTIONAL"]),generationRequired:z.boolean(),sourceMode:z.enum(["REAL_SOURCE","GENERATED","RECONSTRUCTED","POST_PRODUCTION","MANUAL"]),representationType:rep,brief:z.string().min(1),requiredReferences:z.array(z.string()),requiredPreservation:z.array(z.string()),allowedVariation:z.array(z.string()),technicalRequirements:z.array(z.string()),postProductionRequirements:z.array(z.string()),rejectionCriteria:z.array(z.string()).min(1),downstreamAgent:z.string().min(1)})
const lock = z.object({
  lockId: z.string(),
  entityType: z.enum(["CHARACTER", "LOCATION", "OBJECT", "DEVICE", "PERIOD"]),
  name: z.string(),
  attributes: z.array(z.object({
    key: z.string(),
    value: z.string(),
    strength: z.enum(["STRICT", "MEDIUM", "VARIABLE"]),
  })),
})
const transition=z.object({transitionId:z.string(),fromShotId:z.string(),toShotId:z.string(),type:z.enum(["CUT_ON_SOUND","MATCH_CUT","SCREEN_PUSH_IN","FREEZE_FRAME","TEXT_KINETIC","MAP_CONNECTOR","DOCUMENT_SCAN","SILENCE_HOLD","DATA_WIPE","CLEAN_PROTECTION_TRANSITION","DISSOLVE","HARD_CUT"]),reason:z.string().min(1),durationMs:z.number().positive().optional(),soundCueId:z.string().optional(),visualConstraint:z.string().optional()})
const narration=z.object({narrationSegmentId:z.string(),startSec:z.number(),endSec:z.number(),text:z.string(),wordCount:z.number().int().nonnegative(),claimIds:z.array(z.string()),shotIds:z.array(z.string()).min(1),visualRelationship:z.enum(["COMPLEMENT","CONTRAST","PROVE","EXPLAIN","EMOTION","BREATH"]),silenceBeforeMs:z.number().optional(),silenceAfterMs:z.number().optional(),protectionRequired:z.boolean()})
const sound=z.object({soundIntentId:z.string(),shotId:z.string(),type:z.enum(["AMBIENCE","TEXTURE","SYNC_SFX","TRANSITION","IMPACT","TENSION_BED","SILENCE","EVIDENCE_CUE","BRAND_SIGNATURE"]),purpose:z.string(),startSec:z.number(),endSec:z.number(),priority:z.enum(["CRITICAL","HIGH","MEDIUM","LOW"]),narrationProtection:z.boolean(),forbiddenInterpretation:z.array(z.string())})
const qc=z.object({inputApproved:z.boolean(),everySequenceHasFunction:z.boolean(),everyShotHasDuration:z.boolean(),runtimeConsistent:z.boolean(),claimsCovered:z.boolean(),evidenceCovered:z.boolean(),representationSafe:z.boolean(),openLoopsProgress:z.boolean(),payoffCovered:z.boolean(),noRedundantAdjacentShots:z.boolean(),continuityResolved:z.boolean(),assetsWithinBudget:z.boolean(),everyAssetHasDownstreamAgent:z.boolean(),everyTransitionHasReason:z.boolean(),narrationMapped:z.boolean(),soundIntentsMapped:z.boolean(),criticalTextPostProduction:z.boolean(),noUnsupportedVisualClaim:z.boolean(),blockingErrors:z.array(z.string()),warnings:z.array(z.string()),overall:z.number().min(0).max(1)})
export const editBlueprintSchema=z.object({schemaVersion:z.string(),projectId:z.string(),runId:z.string(),scriptVersion:z.string(),editBlueprintId:z.string(),status:z.enum(["DRAFT","NEEDS_REVISION","BLOCKED","EDIT_BLUEPRINT_APPROVED"]),targetRuntimeSeconds:z.number().positive(),estimatedRuntimeSeconds:z.number().positive(),visualIdentityRef:z.string(),sequences:z.array(editSequenceSchema).min(1),shots:z.array(editShotSchema).min(1),assetRequests:z.array(editAssetRequestSchema).min(1),continuityBible:z.object({characters:z.array(lock),locations:z.array(lock),objects:z.array(lock),devices:z.array(lock),periods:z.array(lock),representationRules:z.array(z.object({representationType:rep,labelRequired:z.boolean(),rule:z.string()})),visualStyleRef:z.string()}),transitionPlan:z.array(transition),narrationMap:z.object({segments:z.array(narration).min(1),language:z.string()}),soundIntentMap:z.array(sound).min(1),productionBudget:z.object({limits:z.record(z.string(),z.number()),usage:z.record(z.string(),z.number()),generatedDurationSeconds:z.number(),referenceCount:z.number(),motionComplexity:z.number(),recurringCharacters:z.number(),locations:z.number(),experimentalScenes:z.number(),estimatedReviewMinutes:z.number(),productionMargin:z.number(),exceeded:z.array(z.string())}),dependencyGraph:z.object({nodes:z.array(z.object({id:z.string(),type:z.enum(["REFERENCE","ASSET","SHOT","SEQUENCE","AUDIO_INTENT"]),status:z.enum(["PENDING","READY","BLOCKED"])})),edges:z.array(z.object({from:z.string(),to:z.string(),relation:z.enum(["REQUIRES","FEEDS","PRESERVES","VALIDATES"])}))}),qc,warnings:z.array(z.string()),blockingErrors:z.array(z.string()),nextAgents:z.array(z.string())}).superRefine((v,c)=>{if(v.status==="EDIT_BLUEPRINT_APPROVED"&&(v.blockingErrors.length||v.qc.blockingErrors.length))c.addIssue({code:"custom",message:"Blueprint aprovado contém bloqueios"})})
