import{z}from"zod"

const referenceStatus=z.enum(["APPROVED","REVIEW_REQUIRED","REJECTED"])
const assetStatus=z.enum(["APPROVED","REVIEW_REQUIRED","REJECTED","DEPRECATED"])
const assetType=z.enum(["REFERENCE","START_FRAME","INSERT","ATMOSPHERE"])

export const CalibrationReportSchema=z.object({calibrationId:z.string(),providerId:z.string(),runtime:z.string(),adapterVersion:z.string(),testCases:z.array(z.object({caseId:z.string(),assetClass:z.string(),description:z.string(),requiredScore:z.number()})),requiredDimensions:z.array(z.string()),scores:z.object({identity:z.number(),environment:z.number(),objectGeometry:z.number(),palette:z.number(),lighting:z.number(),composition:z.number(),representation:z.number()}),allowedAssetTypes:z.array(z.string()),blockedAssetTypes:z.array(z.string()),status:z.enum(["PENDING","APPROVED","REJECTED"]),evidenceRefs:z.array(z.string())})

export const ImageProductionConstraintsSchema=z.object({maxJobs:z.number().int().positive(),maxRetriesPerJob:z.number().int().nonnegative(),approvalThreshold:z.number().min(0).max(1),outputDirectory:z.string().min(1),allowProviderMix:z.boolean()})

export const ImageGenerationInputSchema=z.object({schemaVersion:z.string(),projectId:z.string().min(1),runId:z.string().min(1),promptPackId:z.string().min(1),providerPlanId:z.string().min(1),status:z.literal("PROVIDER_PLAN_APPROVED"),visualIdentityRef:z.string().min(1),continuityBibleRef:z.string().min(1),references:z.array(z.object({referenceManifestId:z.string(),promptId:z.string(),references:z.array(z.object({referenceId:z.string(),entityType:z.string(),role:z.enum(["IDENTITY","LOCATION","OBJECT","DEVICE","STYLE","COMPOSITION","EVIDENCE"]),required:z.boolean(),status:z.enum(["APPROVED","REFERENCE_REQUIRED","MISSING"]),locks:z.array(z.string()),forbiddenDrift:z.array(z.string())})),calibrationRequired:z.boolean(),providerAgnosticRequirements:z.array(z.string())})),imageSpecs:z.array(z.object({promptId:z.string(),imagePurpose:z.enum(["REFERENCE","START_FRAME","INSERT","ATMOSPHERE","EVIDENCE_SUPPORT"]),referenceIds:z.array(z.string()),identityLocks:z.array(z.string()),compositionLocks:z.array(z.string()),requestedAspectRatio:z.string(),requestedResolution:z.string().optional(),preserveForVideo:z.boolean(),motionPreparation:z.string().optional(),textPolicy:z.enum(["NO_CRITICAL_TEXT","PLACEHOLDER_ONLY","SOURCE_TEXT_PRESERVE"]),qcChecks:z.array(z.string())})),evidenceSpecs:z.array(z.object({promptId:z.string(),sourceAssetRequired:z.boolean(),sourceAssetIds:z.array(z.string())}).passthrough()),providerExecutionPlan:z.object({providerId:z.string(),adapterVersion:z.string(),executionPlanId:z.string(),jobs:z.array(z.object({jobId:z.string(),promptId:z.string()}).passthrough())}).passthrough(),productionConstraints:ImageProductionConstraintsSchema,calibrationReports:z.array(CalibrationReportSchema),checkpoint:z.unknown().optional()})

const adherence=z.object({identity:z.number(),environment:z.number(),objectGeometry:z.number(),palette:z.number(),lighting:z.number(),composition:z.number(),period:z.number(),narrativeFunction:z.number(),representation:z.number(),technicalQuality:z.number(),overall:z.number()})

export const ImagePackSchema=z.object({schemaVersion:z.string(),projectId:z.string(),runId:z.string(),imagePackId:z.string(),promptPackId:z.string(),providerPlanId:z.string(),status:z.enum(["DRAFT","NEEDS_REVIEW","BLOCKED","APPROVED_FOR_VIDEO"]),referenceAssets:z.array(z.object({referenceId:z.string(),entityId:z.string(),entityType:z.string(),role:z.string(),assetIds:z.array(z.string()),locks:z.array(z.string()),forbiddenDrift:z.array(z.string()),status:referenceStatus,sourceManifestId:z.string()})),generatedAssets:z.array(z.object({assetId:z.string(),imageJobId:z.string(),promptId:z.string(),shotId:z.string(),assetType,assetPath:z.string(),sha256:z.string().length(64),representationType:z.string(),providerId:z.string(),runtime:z.string(),adapterVersion:z.string(),promptHash:z.string(),referenceIds:z.array(z.string()),adherence,hardFails:z.array(z.string()),status:assetStatus,attempt:z.number(),simulated:z.literal(true)})),approvedStartFrames:z.array(z.object({frameId:z.string(),shotId:z.string(),assetId:z.string(),assetPath:z.string(),sha256:z.string().length(64),status:assetStatus,promptId:z.string(),promptVersion:z.string(),referenceIds:z.array(z.string()),preservedAttributes:z.array(z.string()),allowedMotion:z.array(z.string()),forbiddenMotion:z.array(z.string()),composition:z.string(),expectedEndState:z.string(),visualQCId:z.string()})),approvedInserts:z.array(z.string()),approvedAtmosphereAssets:z.array(z.string()),rejectedAssets:z.array(z.object({assetId:z.string(),imageJobId:z.string(),promptId:z.string(),assetType,reasonCodes:z.array(z.string()),adherence,retryable:z.boolean()})),comparisonSets:z.array(z.object({}).passthrough()),calibrationReports:z.array(CalibrationReportSchema),retryHistory:z.array(z.object({}).passthrough()),providerAdherence:z.array(z.object({}).passthrough()),visualQC:z.object({}).passthrough(),budgetUsage:z.object({}).passthrough(),warnings:z.array(z.string()),blockingErrors:z.array(z.string()),nextAgent:z.enum(["PROVIDER_JOB_ORCHESTRATOR","VIDEO_GENERATION_AGENT","HUMAN_REVIEW"])})
