export type AudioPackStatus = "DRAFT" | "NEEDS_REVIEW" | "BLOCKED" | "APPROVED_FOR_ASSEMBLY"
export type AudioBlockingError = "VIDEO_INPUT_NOT_APPROVED" | "NARRATION_FILE_MISSING" | "NARRATION_DECODE_FAILED" | "NARRATION_CLAIM_UNSUPPORTED" | "SFX_FILE_MISSING" | "SFX_DECODE_FAILED" | "SFX_LICENSE_UNVERIFIED" | "SFX_INVALID_TIMESTAMP" | "SFX_NARRATION_COLLISION" | "SFX_CLIPPING_DETECTED" | "SFX_ASSET_NOT_APPROVED" | "SOUND_BIBLE_MISSING" | "AUDIO_QC_FAILED"
export type CueType = "AMBIENCE" | "TEXTURE" | "SYNC_SFX" | "TRANSITION" | "IMPACT" | "TENSION_BED" | "SILENCE" | "EVIDENCE_CUE" | "BRAND_SIGNATURE"

export interface NarrationScriptEntry { segmentId:string; blockId:string; text:string; startSec:number; endSec:number; delivery:string; claimIds:string[]; sourceStatus:"VERIFIED"|"UNCERTAIN"|"UNSUPPORTED"; conditionalLanguageApproved?:boolean; priority:number }
export interface AudioTimelineBlock { blockId:string; shotId:string; startSec:number; endSec:number; claimIds:string[]; representationType:string; preserveOriginalAudio?:boolean }
export interface SoundBible { version:string; brandSound:string; narrationPriority:"absolute"; musicDensity:string; sfxDensity:string; silencePolicy:string; forbidden:string[]; voiceProfile:string; mixProfile:string }
export interface SoundCatalogAsset { assetId:string; catalogId:string; assetHash:string; licenseId:string; licenseVerified:boolean; usageScope:string[]; status:"APPROVED"|"REJECTED"|"REVIEW_REQUIRED"; format:string; durationSec:number; decodable:boolean; tags:string[] }
export interface AudioProviderProfile { provider:string; runtime:string; adapterVersion:string; approved:boolean; capabilities:string[] }
export interface ApprovedAudioVideoClip { clipId:string; shotId:string; status:"APPROVED"; videoJobKey:string; assetHash:string; durationSeconds:number; motionQC:{overall:number}; motionVetos:string[]; provider:string; runtime:string; adapterVersion:string }
export interface CompiledNarrationSegment extends NarrationScriptEntry { renderStatus:"pending"|"rendered"|"rejected"; narrationJobKey:string }
export interface AudioCue { cueId:string; blockId:string; type:CueType; startSec:number; durationSec:number; purpose:string; assetId?:string; assetHash?:string; licenseId?:string; gainDb:number; fadeInMs:number; fadeOutMs:number; duckMusicDb:number; narrationCollision:boolean; status:"planned"|"approved"|"rejected" }
export interface MixPlan { narrationBus:{priority:number;targetGainDb:number}; musicBus:{duckUnderNarrationDb:number}; sfxBus:{duckUnderNarrationDb:number}; ambienceBus:{duckUnderNarrationDb:number}; silenceCues:string[]; masterPolicy:{integratedLufsTarget:number;truePeakMaxDbtp:number;loudnessRangeTargetLu:number;normalization:"twoPass"}; measuredLoudness?:number; analysisPerformed:boolean }
export interface AudioQC { narrationCoverage:number; speechIntelligibility:number; timestampValidity:number; licenseCoverage:number; narrationCollisionRate:number; clippingDetected:boolean; silenceIntegrity:number; soundBibleAdherence:number; overall:number }
export interface AudioRetryRecord { retryId:string; attempt:number; reason:AudioBlockingError; changes:string[]; preservedFields:string[]; status:"SCHEDULED"|"BLOCKED"|"COMPLETED" }
export interface AudioAgentCheckpoint { projectId:string; runId:string; audioPackId:string; stage:"INPUT_VALIDATED"|"NARRATION_COMPILED"|"SOUND_BIBLE_RESOLVED"|"CUES_PLANNED"|"LICENSES_VALIDATED"|"MIX_PLAN_BUILT"|"AUDIO_QC_PASSED"; inputHash:string; artifactHash?:string; createdAt:string }
export interface AudioGenerationInput { schemaVersion:string; projectId:string; runId:string; scriptVersion:string; timelineVersion:string; scriptApproved:boolean; narrationScript:NarrationScriptEntry[]; timelineBlocks:AudioTimelineBlock[]; approvedVideoClips:ApprovedAudioVideoClip[]; soundBible:SoundBible; audioProviderRegistry:AudioProviderProfile[]; soundCatalog:SoundCatalogAsset[]; requestedCues:Array<{cueId:string;blockId:string;type:CueType;startSec:number;durationSec:number;purpose:string;assetId?:string;gainDb:number}>; productionConstraints:{language:string;sampleRate:number;maxRetries:number;audioProvider:string;runtime:string;adapterVersion:string;projectUsageScope:string;qcThreshold:number}; checkpoint?:AudioAgentCheckpoint }
export interface AudioPack { schemaVersion:string; projectId:string; runId:string; audioPackId:string; status:AudioPackStatus; narration:CompiledNarrationSegment[]; cues:AudioCue[]; mixPlan:MixPlan; approvedAudioAssets:string[]; rejectedAudioAssets:string[]; retryHistory:AudioRetryRecord[]; audioQC:AudioQC; blockingErrors:AudioBlockingError[]; warnings:string[]; inputVideoHashes:string[]; narrationJobKey:string; checkpoint:AudioAgentCheckpoint; nextAgent:"FINAL_ASSEMBLY_AGENT"|"HUMAN_REVIEW" }
export interface AudioRenderAdapter { renderNarration(segment:CompiledNarrationSegment,provider:AudioProviderProfile):{assetId:string;assetHash:string;decodable:boolean} }
