export type TopicDecision = "GREENLIT" | "NEEDS_RESEARCH" | "HUMAN_REQUIRED" | "BLOCKED"
export type VisualFunction = "ORIENT" | "SHOW" | "PROVE" | "EXPLAIN" | "CONTRAST" | "EMOTION" | "OPENLOOP" | "PAYOFF" | "TRANSITION" | "BREATHINGSPACE"
export type AssetType = "ESTABLISHING_SHOT" | "HUMAN_ACTION" | "DETAIL_INSERT" | "EVIDENCE_INSERT" | "MECHANISM_GRAPHIC" | "SCREEN_RECREATION" | "TEXT_EMPHASIS" | "MAP_OR_DIAGRAM" | "EMOTIONAL_HOLD" | "CONSEQUENCE_SHOT" | "PROTECTION_GRAPHIC" | "TRANSITION_ASSET"
export interface ProductionConstraints { maxBudgetUnits: number; availableAssetTypes: AssetType[]; wordsPerMinute: number; runtimeToleranceSeconds: number; pauseMarginRatio: number }
export interface TopicBrief { projectId: string; niche: string; country: string; language: string; audience: string; objective: string; targetRuntimeSeconds: number; productionConstraints: ProductionConstraints; editorialConstraints: string[]; researchWindow?: { from: string; to: string } }
export interface TopicCandidate { schemaVersion: string; projectId: string; topicId: string; title: string; coreQuestion: string; angle: string; audiencePromise: string; whyNow?: string; topOfFunnelPotential: number; productionComplexity: number; evidenceAvailability: number; editorialRisk: number; monetizationContext: string; candidateScore: number; confidence: number; sourceRefs: string[]; status: "CANDIDATE" | "GREENLIT" | "NEEDS_RESEARCH" | "HUMAN_REQUIRED" | "REJECTED"; warnings: string[]; blockingErrors: string[] }
export interface GreenlightDecision { selected?: TopicCandidate; rejected: { topicId: string; reasons: string[] }[]; decision: TopicDecision; criteria: Record<string, number>; policy: string; nextStage?: string; warnings: string[]; blockingErrors: string[] }
interface ClaimBase { claimId: string; claimText: string; sourceRefs: string[]; sourceQuality: "PRIMARY" | "SECONDARY" | "LOW" | "MISSING"; sourceDate?: string; supportLevel: number; contradictions: string[]; allowedWording: string; forbiddenWording: string; visualTreatment: "FACTUAL_EVIDENCE" | "DRAMATIZATION" | "ILLUSTRATION" | "NONE"; status: "ACTIVE" | "REMOVE" }
export type EvidenceClaim =
 | (ClaimBase & { classification: "VERIFIED"; sourceRefs: [string, ...string[]]; status: "ACTIVE" })
 | (ClaimBase & { classification: "INFERRED" | "UNCERTAIN"; status: "ACTIVE" })
 | (ClaimBase & { classification: "UNSUPPORTED"; status: "REMOVE" })
export interface EvidenceMatrix { schemaVersion: string; projectId: string; claims: EvidenceClaim[]; unresolvedQuestions: string[]; contradictions: string[]; status: "DRAFT" | "VERIFIED" | "NEEDS_RESEARCH" | "BLOCKED" }
export type VisualJob = { kind: "VISUAL"; job: VisualFunction; description: string; required: boolean } | { kind: "EVIDENCE"; job: "PROVE"; claimId: string; representation: string; required: true }
export type AssetRequest = { kind: "GENERATED"; assetType: AssetType; specification: string; budgetUnits: number } | { kind: "SOURCE"; assetType: "EVIDENCE_INSERT"; sourceRef: string; specification: string; budgetUnits: number } | { kind: "DRAMATIZATION"; assetType: AssetType; disclosure: string; specification: string; budgetUnits: number }
export type TransitionPlan = { kind: "CUT"; rationale: string } | { kind: "DISSOLVE"; durationSec: number; rationale: string } | { kind: "GRAPHIC_MATCH"; matchElement: string; rationale: string }
export interface SoundIntent { soundId: string; beatId: string; intent: "TENSION" | "CLARITY" | "IMPACT" | "SILENCE" | "RELIEF"; description: string }
export interface ScriptBeat { beatId: string; sequenceId: string; startSec: number; endSec: number; section: "HOOK" | "ORIENTATION" | "DEVELOPMENT" | "TURNING_POINT" | "PAYOFF" | "CLOSING"; dramaticFunction: string; informationGoal: string; audienceStateBefore: string; audienceStateAfter: string; mainClaimId?: string; narration: string; delivery: string; claimIds: string[]; evidenceIds: string[]; visualJobs: VisualJob[]; assetRequests: AssetRequest[]; soundIntent?: SoundIntent; transition?: TransitionPlan; openLoopIds: string[]; postProductionRequirements: string[] }
export interface OpenLoop { loopId: string; question: string; openedAtBeatId: string; progressBeatIds: string[]; closedAtBeatId?: string; answerClaimIds: string[]; status: "OPEN" | "CLOSED" | "UNCERTAIN" | "BLOCKED" }
export interface StoryBible { coreQuestion: string; audiencePromise: string; thesis: string; tone: string; structure: string[]; structureDeviationReason?: string }
export interface Sequence { sequenceId: string; title: string; purpose: string; beatIds: string[] }
export interface AssetBudget { generatedVideo: number; generatedImage: number; evidenceInsert: number; motionGraphic: number; mapOrDiagram: number; atmosphericImage: number; manualReviewSlots: number }
export interface AssetUsage { assetType: AssetType; planned: number; budgetCategory: keyof AssetBudget; overage: number; groupable: boolean; recommendation?: string }
export interface EmotionalPoint { atSec: number; intensity: number; label: string }
export interface ContinuityBible { entities: string[]; locations: string[]; chronology: string[]; visualRules: string[]; disclaimers: string[] }
export interface QCFinding { code: string; severity: "WARNING" | "BLOCKING"; message: string; refs: string[] }
export type ScriptQC = { decision: "SCRIPT_APPROVED"; findings: QCFinding[]; estimatedRuntimeSeconds: number } | { decision: "NEEDS_SCRIPT_REVISION" | "NEEDS_RESEARCH" | "HUMAN_REQUIRED" | "BLOCKED"; findings: QCFinding[]; estimatedRuntimeSeconds: number; blockingReasons: string[] }
export interface ScriptPackage { schemaVersion: string; projectId: string; runId: string; topicId: string; status: "DRAFT" | "NEEDS_RESEARCH" | "NEEDS_REVISION" | "SCRIPT_APPROVED" | "BLOCKED"; targetRuntimeSeconds: number; narrationWordCount: number; storyBible: StoryBible; scriptMaster: string; semanticUnits: string[]; sequences: Sequence[]; beats: ScriptBeat[]; openLoops: OpenLoop[]; evidenceMatrix: EvidenceMatrix; assetBudget: AssetBudget; assetUsage: AssetUsage[]; emotionalCurve: EmotionalPoint[]; soundMap: SoundIntent[]; continuityBible: ContinuityBible; qc: ScriptQC; warnings: string[]; blockingErrors: string[]; nextAgent?: string }
