import type{EditBlueprint,RepresentationType}from"./edit-blueprint"
import type{VideoPack}from"./video-generation"
import type{AudioPack}from"./audio-generation"
export type AssemblyBlockingError="ASSEMBLY_INPUT_INVALID"|"VIDEO_PACK_NOT_APPROVED"|"AUDIO_PACK_NOT_APPROVED"|"ASSET_RESOLUTION_FAILED"|"ASSET_HASH_MISMATCH"|"ASSET_LICENSE_MISSING"|"TIMELINE_OVERLAP"|"TIMELINE_GAP_UNAUTHORIZED"|"DURATION_MISMATCH"|"SYNC_REVISION_REQUIRED"|"CAPTION_TEXT_MISMATCH"|"CAPTION_ILLEGIBLE"|"REPRESENTATION_LABEL_MISSING"|"EVIDENCE_INTEGRITY_FAILED"|"UNAPPROVED_ASSET_REFERENCED"|"RENDER_ENCODE_FAILED"|"RENDER_OUTPUT_MISSING"|"OUTPUT_HASH_MISSING"|"OUTPUT_QC_FAILED"
export interface DeliveryProfile{container:string;videoCodec:string;audioCodec:string;resolution:string;frameRate:number;audioSampleRate:number;previewResolution?:string;allowReducedPreview:boolean}
export interface EvidenceBinding{evidenceId:string;shotId:string;assetHash:string;classification:"REAL_EVIDENCE"|"RECONSTRUCTION"|"DRAMATIZATION"|"FICTIONAL_INTERFACE"|"EXPLANATORY_GRAPHIC";verified:boolean}
export interface AssemblyRepresentationRule{representationType:RepresentationType;labelRequired:boolean;labelText?:string;safeAreaValid:boolean;legible:boolean}
export interface TimelineBlockCompilation{blockId:string;startSec:number;endSec:number;videoAssetIds:string[];audioSegmentIds:string[];cueIds:string[];transitionIn?:string;transitionOut?:string;status:"RESOLVED"|"BLOCKED"}
export interface TimelineCompilation{sequenceId:string;blocks:TimelineBlockCompilation[];durationSeconds:number;timelineHash:string}
export interface CaptionCue{captionId:string;segmentId:string;text:string;startSec:number;endSec:number;language:string;claimIds:string[];safeAreaValid:boolean;contrastRatio:number;status:"APPROVED"|"REJECTED"}
export interface CaptionTrack{language:string;cues:CaptionCue[];captionHash:string}
export interface AssetLink{assetId:string;assetHash:string;kind:"VIDEO"|"NARRATION"|"SFX";shotId?:string;blockId?:string;status:"APPROVED";provider?:string;runtime?:string;adapterVersion?:string;durationSeconds:number;frameRate?:number;licenseId?:string}
export interface SyncFinding{assetId:string;blockId:string;expectedStartSec:number;actualStartSec:number;deltaSeconds:number;valid:boolean}
export interface RenderArtifact{renderId:string;kind:"PREVIEW"|"FINAL";outputPath:string;outputHash:string;encoded:boolean;outputExists:boolean;parametersHash:string;createdAt:string}
export interface RenderManifest{renderId:string;projectId:string;assemblyVersion:string;timelineHash:string;videoPackHash:string;audioPackHash:string;captionHash:string;deliveryProfile:DeliveryProfile;outputPath:string;outputHash:string;status:"RENDERED"|"BLOCKED"}
export interface AssemblyQC{timelineIntegrity:number;assetResolution:number;videoAudioSync:number;captionLegibility:number;representationIntegrity:number;evidenceIntegrity:number;continuityIntegrity:number;transitionIntegrity:number;outputTechnicalReadiness:number;overall:number}
export type AssemblyCheckpointStage="INPUT_VALIDATED"|"TIMELINE_COMPILED"|"ASSETS_RESOLVED"|"AUDIO_SYNC_VERIFIED"|"CAPTIONS_VERIFIED"|"PREVIEW_QC_PASSED"|"FINAL_RENDER_COMPLETED"|"OUTPUT_QC_PASSED"|"DELIVERY_APPROVED"
export interface AssemblyCheckpoint{projectId:string;runId:string;assemblyPackId:string;stage:AssemblyCheckpointStage;inputHash:string;artifactHash?:string;createdAt:string}
export interface FinalAssemblyInput{schemaVersion:string;projectId:string;runId:string;assemblyVersion:string;editBlueprintVersion:string;editBlueprint:EditBlueprint;approvedVideoPack:VideoPack;approvedAudioPack:AudioPack;evidenceMatrix:EvidenceBinding[];representationRules:AssemblyRepresentationRule[];deliveryProfile:DeliveryProfile;captionLanguage:string;qcThreshold:number;checkpoint?:AssemblyCheckpoint}
export interface AssemblyPack{schemaVersion:string;projectId:string;runId:string;assemblyPackId:string;status:"DRAFT"|"NEEDS_REVIEW"|"BLOCKED"|"DELIVERY_APPROVED";timelineCompilation:TimelineCompilation;assetLinks:AssetLink[];syncFindings:SyncFinding[];captionTrack:CaptionTrack;previewRender:RenderArtifact;finalRender:RenderArtifact;renderManifest:RenderManifest;assemblyQC:AssemblyQC;blockingErrors:AssemblyBlockingError[];warnings:string[];inputHashes:{videoPack:string;audioPack:string;editBlueprint:string};assemblyJobKey:string;checkpoint:AssemblyCheckpoint;nextAgent:"PACKAGING_AGENT"|"HUMAN_REVIEW"}
export interface FinalAssemblyAdapter{render(kind:"PREVIEW"|"FINAL",manifest:{renderId:string;outputPath:string;parametersHash:string}):RenderArtifact}
