import type{StartFrameRegistryEntry}from"./image-generation"
export type VideoAgentState="RECEIVED"|"START_FRAME_VALIDATED"|"MOTION_MANIFEST_RESOLVED"|"PROVIDER_CALIBRATED"|"GENERATED"|"MOTION_QC_PASSED"|"CONTINUITY_VERIFIED"|"APPROVED_FOR_ASSEMBLY"|"NEEDS_START_FRAME_APPROVAL"|"NEEDS_PROVIDER_CALIBRATION"|"NEEDS_MOTION_REVISION"|"ACTION_OVERLOAD"|"BLOCKED"
export type MotionVeto="MOTION_VETO_01"|"MOTION_VETO_02"|"MOTION_VETO_03"|"MOTION_VETO_04"|"MOTION_VETO_05"|"MOTION_VETO_06"|"MOTION_VETO_07"|"MOTION_VETO_08"|"MOTION_VETO_09"|"MOTION_VETO_10"|"MOTION_VETO_11"|"MOTION_VETO_12"
export interface MotionManifest{motionManifestId:string;frameId:string;shotId:string;allowedMotion:string[];preserveForVideo:string[];primaryAction:string;cameraMotion:string;secondaryMotion:string;endingState:string;forbidden:string[];durationSeconds:number;representationType:string;criticalTextInPost:boolean}
export interface VideoProviderCalibration{calibrationId:string;provider:string;runtime:string;adapterVersion:string;calibrationVersion:string;testCases:string[];requiredDimensions:string[];identityScore:number;geometryScore:number;lightingScore:number;motionFidelityScore:number;endStateScore:number;approvedFor:string[];blockedFor:string[];status:"PENDING"|"APPROVED"|"REJECTED";evidenceRefs:string[]}
export interface VideoProviderRegistryEntry{provider:string;runtime:string;adapterVersion:string;authorized:boolean;capabilities:string[];calibration?:VideoProviderCalibration}
export interface VideoGenerationJob{jobId:string;shotId:string;startFrameId:string;startFrameHash:string;provider:string;runtime:string;adapterVersion:string;motionManifestId:string;finalPrompt:string;parameters:{durationSeconds:number;aspectRatio:string;resolution:string;seed?:string|number;motionStrength:number};attempt:number;createdAt:string;inputHashes:string[];idempotencyKey:string;status:"CREATED"|"GENERATED"|"BLOCKED"}
export interface MotionQC{identityAdherence:number;deviceGeometryAdherence:number;lightingConsistency:number;paletteConsistency:number;compositionStability:number;motionFidelity:number;endingStateAccuracy:number;singleActionCompliance:boolean;technicalQuality:number;overall:number;vetos:MotionVeto[]}
export interface ContinuityComparisonSet{comparisonId:string;shotId:string;startFrameHash:string;firstFrameHash:string;lastFrameHash:string;firstFrameMatch:boolean;lastFrameMatch:boolean;driftDetected:boolean;checks:string[]}
export interface GeneratedVideoClip{clipId:string;jobId:string;shotId:string;assetPath:string;sha256:string;firstFrameHash:string;lastFrameHash:string;status:"APPROVED"|"REJECTED"|"NEEDS_REVIEW";motionQC:MotionQC;motionVetos:MotionVeto[];sourceStartFrameId:string;sourceStartFrameHash:string;provider:string;runtime:string;adapterVersion:string;attempt:number;createdAt:string}
export interface VideoRetryRecord{retryId:string;jobId:string;attempt:number;reason:string;changes:string[];preservedFields:string[];resultingPromptHash:string;status:"SCHEDULED"|"BLOCKED"|"COMPLETED"}
export interface VideoProductionConstraints{aspectRatio:string;resolution:string;maxRetries:number;approvalThreshold:number;maxDurationSeconds:number;outputDirectory:string}
export interface VideoGenerationInput{schemaVersion:string;projectId:string;runId:string;status:"START_FRAMES_APPROVED";startFrameRegistry:StartFrameRegistryEntry[];motionManifests:MotionManifest[];providerRegistry:{providers:VideoProviderRegistryEntry[];selectedProvider:string};productionConstraints:VideoProductionConstraints;checkpoint?:VideoAgentCheckpoint}
export interface VideoAgentCheckpoint{projectId:string;runId:string;videoPackId:string;stage:string;inputHash:string;artifactHash?:string;generatedCount:number;approvedCount:number;rejectedCount:number;reviewRequiredCount:number;warnings:string[];blockingErrors:string[];createdAt:string}
export interface VideoPack{schemaVersion:string;projectId:string;runId:string;videoPackId:string;status:"DRAFT"|"NEEDS_REVIEW"|"BLOCKED"|"APPROVED_FOR_ASSEMBLY";provider:{name:string;runtime:string;adapterVersion:string};generatedClips:GeneratedVideoClip[];rejectedClips:GeneratedVideoClip[];comparisonSets:ContinuityComparisonSet[];retryHistory:VideoRetryRecord[];jobs:VideoGenerationJob[];motionQC:MotionQC;warnings:string[];blockingErrors:string[];nextAgent:"NARRATION_AGENT"|"HUMAN_REVIEW"|"PROVIDER_JOB_ORCHESTRATOR";idempotencyKey:string;checkpoint:VideoAgentCheckpoint}
export interface VideoProviderAdapter{generate(job:VideoGenerationJob,frame:StartFrameRegistryEntry,manifest:MotionManifest):GeneratedVideoClip}
