export type CinematicValidationErrorCode =
  | 'CINEMATIC_SOURCE_PACKAGE_INVALID'
  | 'CINEMATIC_EPISODE_ID_MISMATCH'
  | 'CINEMATIC_SCENE_NOT_FOUND'
  | 'CINEMATIC_SCHEMA_INVALID'
  | 'CINEMATIC_PROTECTED_FIELD_OVERRIDE'
  | 'CINEMATIC_APPROVED_SCENES_REQUIRED'
  | 'CINEMATIC_APPROVED_SCRIPT_REQUIRED'
  | 'CINEMATIC_BEAT_TEXT_MISMATCH'
  | 'CINEMATIC_BEAT_SPAN_OUT_OF_BOUNDS'
  | 'CINEMATIC_BEAT_COVERAGE_INVALID'
  | 'CINEMATIC_BEAT_ORDER_INVALID'
  | 'CINEMATIC_BEAT_CLAIM_INVALID'
  | 'CINEMATIC_BEAT_TIMING_INVALID'
  | 'BEAT_ALIGNMENT_MISSING'
  | 'BEAT_RESEGMENTATION_FAILED'
  | 'BEAT_RESEGMENTATION_NO_MODEL'
  | 'BEAT_DIRECTOR_PARSE_FAILED'
  | 'BEAT_DIRECTOR_SCHEMA_FAILED'
  | 'BEAT_DIRECTOR_NO_MODEL'
  | 'BEAT_DIRECTOR_GENERATION_FAILED'
  | 'CINEMATIC_VISUAL_MODE_REQUIRED'
  | 'CINEMATIC_SHOT_DIRECTION_FAILED'
  | 'CINEMATIC_SHOT_ENUM_INVALID'
  | 'CINEMATIC_SHOT_FOCUS_REQUIRED'
  | 'CINEMATIC_CAMERA_MOTIVATION_REQUIRED'
  | 'CINEMATIC_CAMERA_COMBINATION_INVALID'
  | 'CINEMATIC_SHOT_COMBINATION_INVALID'
  | 'CINEMATIC_CONTINUITY_FAILED'
  | 'CINEMATIC_CONTINUITY_ENUM_INVALID'
  | 'CINEMATIC_CONTINUITY_ORDER_INVALID'
  | 'CINEMATIC_CONTINUITY_RELATION_INVALID'
  | 'CINEMATIC_CONTINUITY_REVERSAL_MOTIVATION_REQUIRED'
  | 'CINEMATIC_CONTINUITY_OWNERSHIP_VIOLATION'
  | 'CINEMATIC_BATCH_COMMIT_FAILED'
  | 'CINEMATIC_FUTURE_FIELD_POPULATED';

export class CinematicValidationError extends Error {
  constructor(
    public readonly code: CinematicValidationErrorCode,
    message: string,
    public readonly details: readonly string[] = []
  ) {
    super(`${code}: ${message}`);
    this.name = 'CinematicValidationError';
  }
}
