import type{AudioAgentCheckpoint,AudioBlockingError,AudioGenerationInput,AudioPack,AudioRenderAdapter,AudioRetryRecord}from"../contracts/audio-generation"
import{AudioGenerationInputSchema}from"../schemas/audio-generation"
import{audioHash,compileNarration,narrationJobKey}from"./narration"
import{validateAudioInput}from"./validation"
import{planCues}from"./cues"
import{buildMixPlan}from"./mix"
import{evaluateAudioQC}from"./qc"
const unique=<T>(items:T[])=>[...new Set(items)]
export function runAudioAgent(input:AudioGenerationInput,adapter:AudioRenderAdapter):AudioPack{AudioGenerationInputSchema.parse(input);const key=narrationJobKey(input),packId=`audio-pack-${key.slice(0,16)}`;const blockingErrors:AudioBlockingError[]=[...validateAudioInput(input)];const provider=input.audioProviderRegistry.find(p=>p.provider===input.productionConstraints.audioProvider&&p.runtime===input.productionConstraints.runtime&&p.adapterVersion===input.productionConstraints.adapterVersion);const narration=compileNarration(input).map(n=>{if(blockingErrors.includes("NARRATION_CLAIM_UNSUPPORTED")||!provider)return n;const rendered=adapter.renderNarration(n,provider);if(!rendered.decodable)blockingErrors.push("NARRATION_DECODE_FAILED");return{...n,renderStatus:rendered.decodable?"rendered"as const:"rejected"as const}});const planned=planCues(input,narration);blockingErrors.push(...planned.errors);const mixPlan=buildMixPlan(planned.cues);const audioQC=evaluateAudioQC(narration,planned.cues,input.soundBible);if(audioQC.clippingDetected)blockingErrors.push("SFX_CLIPPING_DETECTED");if(audioQC.overall<input.productionConstraints.qcThreshold)blockingErrors.push("AUDIO_QC_FAILED");const errors=unique(blockingErrors);const retryable:AudioBlockingError[]=["SFX_NARRATION_COLLISION","SFX_CLIPPING_DETECTED","SFX_LICENSE_UNVERIFIED","SFX_INVALID_TIMESTAMP"];const retryHistory:AudioRetryRecord[]=errors.filter(e=>retryable.includes(e)).slice(0,input.productionConstraints.maxRetries).map((reason,i)=>({retryId:`audio-retry-${i+1}`,attempt:i+2,reason,changes:reason==="SFX_NARRATION_COLLISION"?["movedCueByMs:180","reducedGainDb:3"]:reason==="SFX_CLIPPING_DETECTED"?["reducedGainDb:3","recalculatedHeadroom"]:reason==="SFX_LICENSE_UNVERIFIED"?["replaceWithApprovedEquivalent"]:["trimmedWithFade"],preservedFields:["narrationPriority","scriptText","claimIds"],status:"SCHEDULED"}));const stage:AudioAgentCheckpoint["stage"]=errors.length?"MIX_PLAN_BUILT":"AUDIO_QC_PASSED";const checkpoint={projectId:input.projectId,runId:input.runId,audioPackId:packId,stage,inputHash:audioHash(input),artifactHash:undefined,createdAt:new Date().toISOString()};const pack:AudioPack={schemaVersion:input.schemaVersion,projectId:input.projectId,runId:input.runId,audioPackId:packId,status:errors.length?"BLOCKED":"APPROVED_FOR_ASSEMBLY",narration,cues:planned.cues,mixPlan,approvedAudioAssets:input.soundCatalog.filter(a=>a.status==="APPROVED"&&a.licenseVerified&&a.decodable).map(a=>a.assetId),rejectedAudioAssets:unique(planned.rejected),retryHistory,audioQC,blockingErrors:errors,warnings:mixPlan.analysisPerformed?[]:["LOUDNESS_NOT_MEASURED_BY_MOCK"],inputVideoHashes:input.approvedVideoClips.map(c=>c.assetHash),narrationJobKey:key,checkpoint,nextAgent:errors.length?"HUMAN_REVIEW":"FINAL_ASSEMBLY_AGENT"};pack.checkpoint.artifactHash=audioHash({...pack,checkpoint:{...checkpoint,artifactHash:undefined}});return pack}
